### ISSUE TITLE
Check file exist before anything

### ISSUE THREAD

**Issue by moaz-mokhtar** [magic-wormhole/magic-wormhole.rs#113]
Greetings,

I found issue as below scenario:
- sending a file which is not exist 
- program preparing code and know nothing about missed file.
- receiver typed correct, then waiting.
- sender panic with unclear error, and receiver still waiting to receive.

So we need to:
- check file in host before do anything
- if file not exist no code to be generated but a clear message that file is not exist.

Sender:
![image](https://user-images.githubusercontent.com/5870208/108618054-99539080-7423-11eb-8bcd-372b06e6c9fe.png)

Receiver:
![image](https://user-images.githubusercontent.com/5870208/108618076-c607a800-7423-11eb-905f-9f40df46e8cf.png)

**Comment by piegamesde** [comment]
Good catch, thanks for the report. I'll block this one on #107, because I think it's better to wait for that to be merged before starting to fix it.

**Comment by piegamesde** [comment]
This issue is now ready to be worked on.
