### ISSUE TITLE
Publish 0.1.0 to crates?

### ISSUE THREAD

**Issue by okdistribute** [magic-wormhole/magic-wormhole.rs#118]
The latest version I see published is 0.0.2, is that intentional?

Thanks! Looking forward to using this in a project.

**Comment by piegamesde** [comment]
I haven't bothered much about releases yet, to be honest. Also, I never published a crate yet and @warner owns the access …

How badly do you need this? Personally, I am fine with putting this on the backlog until the API is stable enough for people to actually be able to use this as a library.

**Comment by okdistribute** [comment]
All good, I just found [portal](https://github.com/landhb/portal) which i can use instead, seems to do the trick! Thanks for the quick response!

**Comment by piegamesde** [comment]
Thanks for digging up `portal`, it looks really interesting. But just to make it clear: you can totally already use Magic Wormhole as a library dependency in your project, a few already do so. But:

- You'll be best off using it from git like `{ git = https://github.com/magic-wormhole/magic-wormhole.rs }`; the releases aren't really worth much at this point in development
- Expect to adapt your code as things change
- Be prepared to contribute to the project :)

**Comment by okdistribute** [comment]
Thanks @piegamesde for the tips!

I would love to use it still, but as you might expect using a git repository directly can be quite troubling at times, for example, if an update or breaking change is made and some behavior of my program begins to behave in an unexpected manner.

I'd be happy to adapt my code as things change and be prepared to contribute to the project! Having some semver though I think would be really helpful to keep all client libraries stable. Periodic release cycles would include bug fixes as a patch release and new features as a minor. I think contrary to popular belief these open source libraries run by volunteers benefit from this semver (especially) in an alpha stage where things could change unexpectedly!

Happy to help with this if you need, as I'll be working on this project for the next 4 months or so and would love to try to use magic wormhole directly rather than creating my own rudimentary thing.

Cheers, K

**Comment by piegamesde** [comment]
You can already use the release with `{ git = "https://github.com/magic-wormhole/magic-wormhole.rs", version = "0.1.0" }` (or something similar, I haven't looked it up in the Cargo documentation). Quite a lot has changed since then, I'll try to release a 0.2.0 soon-ish, but there are a few bugs I'd like to see fixed first.

**Comment by piegamesde** [comment]
I'll do a `0.2.0-rc1` release hopefully soon, as there are still one or two bugs that I have to fix. But it'll be API-compatible to the final `0.2.0` release later on. Does that suit your needs?

**Comment by piegamesde** [comment]
Version 0.3.0 has been released. The release will also be published on crates.io as soon as `async-std` has made a release.
