### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by piegamesde** [magic-wormhole/magic-wormhole.rs#123]
It would be cool if the `send` command automatically copied the the code to the clipboard.

**Comment by nsmlzl** [comment]
The CLI is supposed to run under Windows, macOS and Linux (X11 and Wayland), or? Any other platforms to consider?
Could we just use the [rust-clipboard](https://github.com/aweinstock314/rust-clipboard) crate? I did a quick test under X11 and Wayland; it seemed to work fine there.

Should the command be automatically copied? Or should we add a command line argument? E.g. [pass](https://git.zx2c4.com/password-store/about/) has a ```--clip``` argument.

Should we inform the user about the new data in the clipboard? Might be informative for new users, but would also add clutter to the output.

**Comment by piegamesde** [comment]
I'd like to consider as many platforms as possible, of those where the application already runs. `rust-clipboard` looks fine, but it does not seem to have native Wayland support. This shouldn't be a problem as long as XWayland is a common thing, but we may want to look into this in the future.

> Should the command be automatically copied? Or should we add a command line argument? E.g. pass has a --clip argument.

That's a hard question. I asked a few people, and not all were enthusiastic about writing stuff to the clipboard. So if we make it a flag, should it be opt-in or opt-out? I fear that independently of that decision, half of the users will be unhappy about this. Maybe the best thing is to make this a persistent configuration option?

An alternative that I thought of would be "press some shortcut to copy the code to the clipboard". But I can't think of any good shortcuts that aren't captured by terminal emulators, so what do you think about "press enter to copy the code to the clipboard"?

> Should we inform the user about the new data in the clipboard?

Yes, absolutely, unless the action was explicitly requested by the user in the first place. I don't think that it would be cluttering the output.

**Comment by corbinu** [comment]
I would make it off by default but maybe print a message informing people they can use it.

**Comment by nsmlzl** [comment]
Is somebody already working on this issue? Or could I have a shot at it?

I was thinking about adding a ```--clip``` argument and also do a check for an environment variable (users could just add it to their bashrc to do a permanent configuration). Or does wormhole have its own configuration file? 

> An alternative that I thought of would be "press some shortcut to copy the code to the clipboard". But I can't think of any good shortcuts that aren't captured by terminal emulators, so what do you think about "press enter to copy the code to the clipboard"?

I was thinking about adding a dialogue asking if the string should be copied (similar to the dialogue during receive). However, in this case I think we would need a second thread, because we are at the same time waiting for the connection to the receiver. I don't know if the added complexity would be worth it? Or did I miss something?

**Comment by piegamesde** [comment]
> Is somebody already working on this issue? Or could I have a shot at it?

Great, I'll assign you.

> Or does wormhole have its own configuration file?

No, not yet. I'm trying to push this back for as long as possible, but I'm confident we'll have to add one *some day*, sooner or later. You can be the person adding one if you want to. You can also do CLI flags or environment variables or whatever you like most, I'm fine with it and it can always be changed later on.

> However, in this case I think we would need a second thread, because we are at the same time waiting for the connection to the receiver.

We are using an async frameworks, so concurrent tasks are not a problem.

**Comment by piegamesde** [comment]
I propose the following implementation to get things started:

- After the connection is established, the user is prompted whether they want to copy the password to clipboard.
- The default option is "yes", so pressing enter will copy it.
- They can enter "n[o]" to not copy it.
- They can also ignore the prompt. In that case, the prompt will abort as obsolete as soon as the other side connects.

**Comment by rpls** [comment]
I gave it a first shot in #134!

**Comment by piegamesde** [comment]
@nsmlzl I see that you've made a few commits on your fork. Would you mind publishing them as a draft PR in the meantime?

**Comment by rpls** [comment]
#134 is a draft PR
