### ISSUE TITLE
Bad license badge in README.md

### ISSUE THREAD

**Issue by Max1Truc** [magic-wormhole/magic-wormhole.rs#144]
The little "license" badge, on the bottom of the README.md file, says the repository is licensed under the MIT license while the repository seems licensed under the EUPL license.

**Comment by piegamesde** [comment]
I don't see any mistake in the README file itself. So probably the image is still wrong in the cache. Initially I'd hoped that it'd update by itself after some time, but given how long ago the license change was this probably won't happen anymore.

I suggest removing the badge from the README entirely. It give little benefit and also we have an entire section about the topic just above it.
