### ISSUE TITLE
Gather transit connection information programmatically

### ISSUE THREAD

**Issue by felinira** [magic-wormhole/magic-wormhole.rs#150]
At the moment it seems like it is not possible to programmatically gather information about the used connection method and IP address / relay hostname during a transfer, at least not when using `transfer::send_file` and similar.

Would it be possible to make `request::accept` and `transfer::send_file` return some sort of informational struct once the transfer has started?

**Comment by felinira** [comment]
While more information is always nice, this would already help. IP addresses would be nice to have, too, but not particularly important.

**Comment by felinira** [comment]
Thanks! That was fast :)

**Comment by piegamesde** [comment]
Doing my best ^^
