### ISSUE TITLE
Add 32bit build on Windows

### ISSUE THREAD

**Issue by gyger** [magic-wormhole/magic-wormhole.rs#156]
I sometimes use magic-wormhole to access old laboratory computer, that unfortunately run sometimes old 32bit computers.
The port forward feature looks exciting for this use-case, so I am wondering if it is possible to get 32 bit builds.

I do understand if that is not wanted, just wanted to ask.

**Comment by piegamesde** [comment]
You are welcome to try out getting it to work of course. But for my part, the main motivation for supporting Windows at all is "they have a lot of market share", which certainly does not apply to Win32 :)

**Comment by piegamesde** [comment]
For cases where you want to transfer files instead of port forwarding, the folks from the [Go implementation](https://github.com/psanford/wormhole-william) seem to provide Windows i386 builds with their releases. You could download and try out that, all Wormhole clients should be interoperable anyways.

**Comment by gyger** [comment]
Thanks for your help. I compiled it using rustup and 32bit, worked fine. I fully understand your point, it is a niche operating system by now, that should also not be supported. :)

**Comment by piegamesde** [comment]
I'm glad to know that it works. If you got it to work without modifications, you could add a step to build them in the CI (look for the "dist" job) and I'd then add those binaries to the releases. I don't mind supporting Windows 32 as long as it creates no extra work for me :)
