### ISSUE TITLE
Detect broken TCP connection to peer

### ISSUE THREAD

**Issue by felinira** [magic-wormhole/magic-wormhole.rs#166]
This is related to #165 but a bit of a different take on the issue.

Reproduction steps:
-   sending file from wormhole-rs
-   receiving from wormhole-python
-   aborting the wormhole-python transfer
-   wormhole-rs will stall

Wormhole-rs should probably detect (maybe after some timeout?) that the other peer is not reachable anymore and throw an error. At least in my experience this doesn't seem to be the case.

**Comment by piegamesde** [comment]
I'd have to test this, but probably this is already happening except that the timeouts are way too high (TCP has a default of 2h or something on most Linuxes?).
