### ISSUE TITLE
feature request: support ssh invite/ssh accept modes

### ISSUE THREAD

**Issue by karlicoss** [magic-wormhole/magic-wormhole.rs#182]
The python wormhole has ability to send/receive SSH keys. Any chance of supporting it here? Thanks!

**Comment by piegamesde** [comment]
Hi, that's most certainly a niche feature. I've never used it myself, so honestly I don't really know what the use case is here, especially why `ssh-copy-id` doesn't work out for you?

**Comment by karlicoss** [comment]
ssh-copy-id requires some method of authentication already set in place, wormhole comes very useful when you have passwordless-only ssh

**Comment by piegamesde** [comment]
But if you have a passwordless ssh connection, you're already done?

**Comment by karlicoss** [comment]
Not really, you might have it from a different computer, but not from the
one you're trying to setup. Or you might have access to both machines
physically, but no ssh keys shared between them yet.

**Comment by piegamesde** [comment]
https://github.com/psanford/wormhole-william/issues/54

I agree with the discussion over there: ideally, wormhole-rs would handle this case sufficiently well without having to specially handle this exact use-case. And I acknowledge that this currently is not the case, given that currently there is no easy way to do shell redirects and such.

If you absolutely want the exact original functionality, I suggest writing a separate tool for that. wormhole-rs has a separate library component so it should not be any harder than implementing it in here.
