### ISSUE TITLE
figure out API-error return pathway

### ISSUE THREAD

**Issue by warner** [magic-wormhole/magic-wormhole.rs#23]
API errors are things like calling `w.set_code()` twice, or using a badly-formatted code, or calling `w.derive_key` before the key has been established. In the Python code, these are exceptions that are raised synchronously while processing the API call.

In the Rust version, we could do the same (which means defining some error classes, and changing some function signatures to return `Result`, and probably changing the top-level WormholeCore entry point to return a `Result` too).

Or we might do something more asynchronous, and emit "error" events along with the other API actions that go out. The challenge with this approach is how to correlate the errors with the pending API call that's responsible for them.

The API/IO glue layer has to decide how to present errors. If it's providing Futures to the application, then it probably wants to return a Future that errbacks (rather than returning `Result<Future<..>>`. That doesn't obligate the WormholeCore to deliver errors asynchronously: the glue layer could react to a synchronous error by returning a pre-failed Future (the equivalent of `twisted.internet.defer.fail(exception)`).

One other thing to consider is how much state might have been changed at the time we decide to signal an error. Maybe Boss (which handles all API calls) should do its error checking before firing any other events, and no other machine should be allowed to signal an error.

We should also think about the `close()` API, which in Python is defined to return a Deferred that fires when all network and timer operations have stopped (so all sockets are closed, all cleanup is done). `close()` signals an error if the wormhole was unable to connect, which includes cases like:

* the network connection to the Rendezvous/Mailbox server couldn't complete the first time (with information about the error, so the user can figure out if the server is offline, if their DNS resolution is broken, or if they're simply not on the internet right now)
* we connected, but we were interrupted before hearing from the other side (aka "Lonely")
* we connected, but at some point we received a badly-encrypted message, which indicates a man-in-the-middle attack (aka "Scared")

**Comment by piegamesde** [comment]
As of #94, all programmer related errors are eliminated at compile time by the type system. `core` sends any errors it has over the channel as `APIEvent::GotError`. The public API exposes this as a stream of `Result<message type, error type>`.
