### ISSUE TITLE
figure out Transit

### ISSUE THREAD

**Issue by warner** [magic-wormhole/magic-wormhole.rs#25]
In the Python code, `Wormhole` is the object that does the PAKE-based key agreement and then gets you queued delivery of small messages. There's a separate object named `Transit` which gets you a direct TCP connection (possibly going through a "transit relay"), encrypted with a "transit key", using "connection hints" that are delivered through the Wormhole channel. The CLI tool builds the Wormhole, then sends an "offer" through the wormhole describing what it wants to send to the recipient (text message, file, or directory). If it's a file or directory, it includes the Connection Hints from its Transit object, and gets hints from the recipient (which it then submits to its Transit). Once the Transit connection is established, the file/directory is streamed through it.

I'm working on replacing Transit with a feature named "Dilated Wormholes", in which the direct-connection is managed by the Wormhole object itself, using a new API named `w.dilate()`. This will make it much easier to send multiple files over the same connection, or to send them in either direction, on demand. We'll need this to build a proper GUI in which either side can drag+drop files into the application window and see them sent to the other, regardless of which side initiated the original connection.

But, to build a tool that can interoperate with the current (0.10.5) python version, we'll need to implement Transit in Rust. https://github.com/warner/magic-wormhole/blob/0.10.5/src/wormhole/transit.py is the relevant code, and https://github.com/warner/magic-wormhole/blob/0.10.5/docs/transit.md has the docs.

We'll probably need to extend the IO/API layer to support Transit (and Dilation in the future), with actions like:

* create an outbound TCP connection, notify on connection, write data to it, receive data from it
* open a listening socket, learn its TCP port number
* enumerate the host's IP addresses
* get notifications when the outbound write queue is full, so we can pause production of transit data
* tell the IO layer to pause receipt of data, since our inbound queue is full
* allow the application to ask to open a new transit/dilation channel, write data to it, receive data from it, pause it, be paused by it, resume/be-resumed, close, be notified about close

It might make sense for the API layer to provide connect/listen functions that look like that platform's native network-socket connect/listen facilities. For Rust in particular, the thing that you write data to should probably have the same Trait as a native TCP socket, so other protocols can be layered on top easily.

**Comment by vu3rdd** [comment]
@warner I have implemented most of the transit in a branch. The not so good news is that I branched off from a very old version and magic-wormhole.rs has probably changed quite a bit after that. Nevertheless I will make an attempt to rebase the changes on top of the current latest and try to send you PRs. fwiw, here is the branch with transit protocol implemented 

https://github.com/vu3rdd/magic-wormhole.rs/tree/file-transfer

(relay etc are all implemented and most likely there are bugs in that implementation which are not ironed out yet - also only blocking io so far because I just wanted to get it working as a first step and I haven't figured out async io on rust yet)

**Comment by warner** [comment]
Oh wow, awesome. Yeah, let me know when you've rebased it and I'll take a look.

**Comment by piegamesde** [comment]
I went ahead and rebased (okay, "rebased") it: #89.

**Comment by piegamesde** [comment]
Transit is mostly figured out now (see #94), closing.
