### ISSUE TITLE
cost analysis of various type conversions

### ISSUE THREAD

**Issue by vu3rdd** [magic-wormhole/magic-wormhole.rs#31]
Right now, we are generously using `.as_bytes()`, `.clone()`, `to_vec()` and so on without caring much about the cost involved in the conversion (like Copying). We need to look at the code that gets generated and see if we can eliminate as many of them as we can by using the right types where ever possible.

**Comment by piegamesde** [comment]
Most of these can be eliminated by not taking owned types as function arguments, e.g. `String` -> `&str`, `Vec<T>` -> `&[T]`. I already started to do this on the `blocking` module and it helps get rid of a lot of `clone`s, `to_string` and `to_vec` calls.

`as_bytes` should be a no-op as per convention.

**Comment by piegamesde** [comment]
I think with the newest changes from #94, the situation is a lot better. There are still a few things that are cloned (e.g. some keys) and might be improved, but nothing really bad.
