### ISSUE TITLE
make new crate(?) for client-to-client transfer protocol code

### ISSUE THREAD

**Issue by warner** [magic-wormhole/magic-wormhole.rs#50]
In #48 @copyninja improved the demo code that performs the equivalent of `wormhole send --text=`, using some `struct`s to encapsulate the client-to-client messages like Offer and Answer and Error.

I'm thinking we should put this code in a separate crate, or at least a separate module. `WormholeCore` doesn't know anything about the protocols run on top of a wormhole, it just provides the `w.send()` and `w.get_message` calls to convey the messages used to implement such protocols. The entire `core/examples/` directory should probably go away, moved into maybe `io/blocking/examples` or `io/tokio/examples` depending upon what sort of IO it uses.

I want to use the future `magic-wormhole` crate to contain the file-transfer executable, so `cargo install magic-wormhole` gets you a `wormhole` binary that behaves mostly like the Python version. We could put all the transfer-related stuff into that, so to get `~/.cargo/bin/wormhole` you would `cargo install magic-wormhole` and you'd get three crates installed: `magic-wormhole`, `magic-wormhole-io-blocking` (or `-tokio` if we go that route), and `magic-wormhole-core`. Applications which want to use wormholes for provisioning would just depend on `magic-wormhole-io-blocking` (or `-tokio`), which would pull in `magic-wormhole-core` but not `magic-wormhole`.

One open question is whether other applications might want access to the text- or file- transfer portions of the `wormhole` executable, but in library form. I'm not 100% convinced that this is likely, but if it is, we might want to split `magic-wormhole` into a small `cargo init --binary` crate (named `magic-wormhole`) that installs the executable, and a larger `--library` crate that contains everything else. so those apps can get the library without the executable. *If* we go that way, then the `Offer` and `Answer` messages (and the rest of client-to-client stuff) would go in that library.

Another question is where the `Transit` code (which I think @vu3rdd was hoping to tackle) should go. In the current protocol, it's mostly independent of the `wormhole` library: it produces messages that need to be delivered safely to the other `Transit` instance (so we drop them into `w.send()`), but that's it. So maybe we should make a new crate named `magic-wormhole-transit` for it. There's not much sans-io protocol to be written, I think it'll need to depend upon a particular IO style right off the bat, but maybe there's an argument for having both `magic-wormhole-transit-blocking` and `magic-wormhole-transit-tokio`, I don't know.

The upcoming `Dilation` protocol work *is* much more tightly integrated into the `Wormhole` object, so that will need to go somewhere else. I haven't figured very much about this out yet. The Python version is all very Twisted-centric, and `w.dilate()` returns a Deferred that fires with a trio of Endpoints, and then you can run normal protocol connections or Listeners over those endpoints. The Rust equivalent is going to look like the normal TCP socket API (which could be like `std::net::TcpStream`, or some Tokio/Mio equivalent). So maybe we say that the Dilation API's IO framework will match the rest of the Wormhole's IO framework, which would mean that `magic-wormhole-io-blocking` gets you a Dilation-capable `Wormhole` object with an API that resembles `std::net::TcpStream`. And `magic-wormhole-io-tokio` gets you one with a Tokio-flavored Dilation API. The shared parts of the Dilation protocol might go in `magic-wormhole-core`, or maybe in a separate shared crate (`magic-wormhole-dilation-core`?) since I think there *might* be enough sans-io -style code to make that worthwhile. I dunno, I need to finish the Python work on Dilation first, and that's going slowly.

**Comment by warner** [comment]
@copyninja and I were just talking about this. I suggested starting with a module in `magic-wormhole-core` named `transfer.rs`. Later, we should create a new binary crate named `magic-wormhole` in a top-level `app` directory, and move `transfer.rs` into that. We can then build the command-line tool in that new crate.

**Comment by copyninja** [comment]
I've created PR #52 by moving peer messages

**Comment by warner** [comment]
Now that we're using a single crate, this should probably live in a module named `transfer` (which is a sibling of `core`, and imports/uses it), rather than a separate crate. `transit` should do the same. And when Dilation lands, we can use the same pattern.

**Comment by piegamesde** [comment]
> Now that we're using a single crate, this should probably live in a module named transfer (which is a sibling of core, and imports/uses it), rather than a separate crate. transit should do the same. And when Dilation lands, we can use the same pattern.

This is what is happening now as of #94. Can this issue be closed then? Regarding multiple crates: I'd like to keep one library for all protocols, but we can feature gate the individual modules if needed.
