### ISSUE TITLE
Portability to Windows platform

### ISSUE THREAD

**Issue by copyninja** [magic-wormhole/magic-wormhole.rs#53]
Currently magic-wormhole.rs does not compile on Windows due to use of libsodium which is not natively available on Windows. Is there any alterantive to libsodium which we can rely on?. Or is there a way to provide crate for Windows?. Probably we should look at how cargo does it?. 

I know this is not priority right now but I just thought of keeping this on our radar.

**Comment by warner** [comment]
Excellent point.

My hope would be for a native Rust implementation of the pieces of libsodium that we need. That'd be better in one sense: native Rust means memory safety.

But it'd be worse in another sense: part of the appeal of libsodium is that it uses DJB's original code, which is very fast and very carefully written (constant-time operation), but that code is in C, and both the speed and the constant-time properties depend intimately on the details of how C gets compiled, so porting those aspects won't be an easy task.

We don't especially need the speed. The constant-time-ness would be nice, though.

For reference, we use libsodium for the `SecretBox` authenticated-encryption function, which is used to protect all messages sent after the PAKE exchange emits a shared key. We don't use the asymmetric `Box` function, nor any of the key-agreement tools. So we might be able to get by with a less-than-complete port.

I haven't looked at crates.io to see what else is out there. I have to imagine that somebody's made a stab at a pure-Rust implementation, but I've no idea how far along such a port might be, nor any idea about it's quality.

I guess one option is to use different crates on windows vs unix, maybe sacrificing some speed/quality properties on the platform that can't use the C libsodium.

**Comment by copyninja** [comment]
I was checking sodiumoxide code and from readme it should work on Windows if properly compiled libsodium is available on target machine. I also checked git2-rs code which is crate which even cargo depends on, there they embed source and compile it in place if its not found on target machine.

Even if sodiumoxide can put original source in the crate, it should still need native or cygwin compiler at its disposal to work. So we will probably back to square one :).

May be we should consider shipping prebuilt binary?. May be using appveyor help?.

**Comment by warner** [comment]
Yeah, if/when we decide to ship executables, making precompiled ones for windows is probably the right way to go. I've got appveyor building similar things for Tahoe-LAFS, so I'd follow that model.

**Comment by piegamesde** [comment]
Is this issue still relevant? I managed to compile Wormhole using MinGW and it works fine, I don't fully understand what the original issue was and what exactly has changed since then so that it works.

**Comment by piegamesde** [comment]
Closed with #121
