### ISSUE TITLE
w.input_code support in io crates to support different input style clients. (eg. Android)

### ISSUE THREAD

**Issue by copyninja** [magic-wormhole/magic-wormhole.rs#55]
I was just wondering how to put in `w.input_code` in `io/blocking`. Does `io/blocking` should provide tab completion using `rustyline` or `w.input_code` should simply initialize `InputMachine` and leave it to app using `io/blocking` to complete tab completion logic?.

I think letting app do the hard work seems correct way as `w.input_code`  can have different meaning in different kinds of client. @vu3rdd and me were discussing cross compiling `wormhole_core` to Android and developing an Android app where he brought up that tab completion is probably meaning less for Android apps and scanning qr code is more meaningful. In such cases probably `w.input_code` will be simply scan qr code and use `w.set_code`. 

Thought of documenting this here before I forget the discussion. 

PS: feel free to make title more readable :).

**Comment by copyninja** [comment]
>BTW for GUI apps, the box into which you type the code can make a popup listbox to help with completion, if it makes sense graphically. I tried to design the completion API to support this kind of UI too (the completion API doesn't have to be driven by readline, and it doesn't print anything, it just returns lists of strings that the frontend can display however it likes).

This makes sense.

>In particular, the InputHelper returned by w.input_code won't block when you ask it for completions: it will just return (immediately) some list of strings based upon the most recent update it got from the server (i.e. from the WormholeCore).

In our case we do not have separate `InputHelper` its just part of `Input` machine. So `w.input_code` can start the `Input` machine at the most. But that will not help the applications, more below.

>I don't think io/blocking should import or use rustyline (although it'd be reasonable for the examples to use it, so maybe it could go into the devDependencies). Although, it might be kind to provide some sort of glue/bridge/adapter between the InputHelper API and rustyline, like we do for readline in the python version. But I don't want that to force a dependency on apps that don't use it. Maybe we should add a feature(rustyline) to enable that adapter?

Yeah adding a external dependency specific to tab completion is like forcing application to rely on one specific crate. (Though I think currently rustyline is only readline like feature providing crate in rust). But as I said above we don't have `InputHelper` and since in tab completion we need to interact directly with `Wormhole` object, we should provide some sort of wrapper from `io` crate which provides helper method and allows the application  to get what it needs like in `readline.rs` example of core.

Making `rustyline` as a feature is reasonable but we need some helpers to allow application to utilize tab completion.

**Comment by piegamesde** [comment]
During my refactorings of the core, the input listing feature got cut. Sorry about that. It'll probably have to be re-implemented completely from scratch again, so this issue is obsolete now.
