### ISSUE TITLE
implement w.derive_key, decide ownership of key/verification stuff

### ISSUE THREAD

**Issue by warner** [magic-wormhole/magic-wormhole.rs#67]
As mentioned in https://github.com/warner/magic-wormhole.rs/issues/9#issuecomment-379272954 , we still need to implement the top-level `w.derive_key(purpose)`, and make sure it can only be called when we've got a verified key.

**Comment by piegamesde** [comment]
I think with the new public API (see #94), this cannot happen anymore. The key is only exposed to the user once it's verified.
