### ISSUE TITLE
possible message-inversion in Order state machine

### ISSUE THREAD

**Issue by warner** [magic-wormhole/magic-wormhole.rs#68]
As mentioned in https://github.com/warner/magic-wormhole.rs/issues/13#issuecomment-378428542 , there's probably a particular sequence of input messages that would violate the expectations of the Receive machine, which we need to deal with.

**Comment by piegamesde** [comment]
Is this issue still present? The receive machine has changed a lot recently, but I don't understand the original issue enough to tell if this still might happen.
