### ISSUE TITLE
State of the project

### ISSUE THREAD

**Issue by piegamesde** [magic-wormhole/magic-wormhole.rs#88]
Hi, I'm really interested in this project and would like to know what's its current development state is. I'm considering to contribute to it, but I'd need some guidance for a start: which issues need tackling and how to get familiar with the code.

Some "help wanted" and "good first issue" labels might help for orientation.

**Comment by vladimir-lu** [comment]
Same here

**Comment by piegamesde** [comment]
So, for anyone interested, I'm trying to continue development over at [my fork](https://github.com/piegamesde/magic-wormhole.rs) until we (hopefully) get a response from the original authors one day. Any help is welcome!

**Comment by piegamesde** [comment]
I am very happy to be able to announce that this project not dead! The code base now has finally reached a point where the core is complete and stable enough to actually build cool applications on top of it.

**For anybody wanting to contribute**, I've tagged issues with [good first issue](https://github.com/magic-wormhole/magic-wormhole.rs/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) and with [help wanted](https://github.com/magic-wormhole/magic-wormhole.rs/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) that I deem doable even for those unfamiliar with the code base. I'll provide help and guidance as good as I can, simply ask in the respective issues if you're stuck. Now is a great time to join, there are a lot of low hanging fruits to get familiar with the code base.

Again, many many thanks to @warner for everything he's done to the project, as well as @vu3rdd for the initial transit+transfer implementation and to all those who helped build the core.
