### ISSUE TITLE
Error handling with serialization

### ISSUE THREAD

**Issue by piegamesde** [magic-wormhole/magic-wormhole.rs#97]
Error handling is a big mess right how, but this is maybe the easiest one to fix. All structs that are send expose a `serialize`/`deserialize` method that delegates to `serde_json` together with `unwrap()`. This should be cleaned up. Errors need to be exposed. Maybe we should inline all of them and get rid of them entirely?

**Comment by vishalsodani** [comment]
I would like to help. Can you please explain what do you meant by "Errors need to be exposed. inline all of them and get rid of them entirely ?"

**Comment by piegamesde** [comment]
Great!

> Errors need to be exposed.

Well, we have a lot of functions like [this](https://github.com/magic-wormhole/magic-wormhole.rs/blob/master/src/core/server_messages.rs#L102-L104) in the code base that panic. They need to return a `Result` which needs to be handled correctly.

> inline all of them and get rid of them entirely

I'm referring to those `serialize`/`deserialize` methods for which it may be better to inline their code where it's used.
