### ISSUE TITLE
[transfer] Give progress information

### ISSUE THREAD

**Issue by piegamesde** [magic-wormhole/magic-wormhole.rs#98]
In order for the CLI to display a fancy progress bar, the transfer API needs to expose such information. Together with progress, we probably want to track transfer speed.

One possibly way to implement this is to pass some callback to the file transfer that calls the method once something happens. The alternative way would be to spawn the file transfer (or the UI updating) in a new task and let them send events over a channel. Note that the latter can be implemented using the former outside of the API (by having the callback writing into a channel).

The difficulty I see here is to know when the caller should be informed. After every packet? Every percent? Every second? Probably some combination of multiple. Can the transfer expect the UI updating to be reasonably quick? Otherwise we a forced to make this multiple tasks.

**Prior art/related work:**

- [progress-streams crate](https://docs.rs/progress-streams/1.1.0/progress_streams/): Wraps a `Reader`/`Writer` using the callback approach. Not sure if this fits us as we are on a higher abstraction level.

-----

The actual CLI implementation is secondary to this issue. Of course, it make sense to develop both together in order to test the ergonomics of the API, but we can always make the output pretty later on. There are plenty of fancy progress bar crates out there :)

**Comment by brightly-salty** [comment]
Just wanted to put indicatif out there as a possible crate to help with this. You can provide it a callback and an optional theme and it will do the behind-the-scenes.
https://docs.rs/indicatif/0.15.0/indicatif/

**Comment by moaz-mokhtar** [comment]
This is 2nd time to me to contribute in Rust project. Can I do a try?
I did a research and tried but found below:
1. progress-streams: have errors when implementing the sample code in the doc. That is why I preferred to check alternatives.
2. pbr: I found this crate which defined as: *Console progress bar for Rust Inspired from pb, support and tested on MacOS, Linux and Windows.*
    - Sample:
        ![image](https://user-images.githubusercontent.com/5870208/107549999-2a7f6780-6bd9-11eb-84a4-18971ae707c5.png)

**Comment by piegamesde** [comment]
Sure, go ahead :)

I haven't tried `progress-streams` myself so I can't judge on it. Have you already found any alternatives?

I'd like to keep the scope of this issue small and mainly focus on the library part of it. For now, a few print statements on the application side will be fine, just enough to see that it's working.

**Comment by moaz-mokhtar** [comment]
The alternate will be [pbr](https://crates.io/crates/pbr).

Regarding the scope, I understand that I have to do below:
- Show transfer data progress in the console.

Is that correct? if something different define me the requirements.

**Comment by piegamesde** [comment]
Go ahead.

**Comment by crd477** [comment]
I also just learned about [Linya](https://lib.rs/crates/linya).  It claims to "stick to Rust basics and offers a smaller feature set than alternatives, but is _very_ efficient and also intuitive to use".
This one might also be a good option.

**Comment by moaz-mokhtar** [comment]
> I also just learned about [Linya](https://lib.rs/crates/linya). It claims to "stick to Rust basics and offers a smaller feature set than alternatives, but is _very_ efficient and also intuitive to use".
> This one might also be a good option.

I did read about that yesterday. I don't have info which is better pbr or Linya.

**Comment by moaz-mokhtar** [comment]
I did create a branch named "progress_bar" but I didn't commit or push.
Progress bar implemented when sending data as below screenshot:
![image](https://user-images.githubusercontent.com/5870208/107869236-93decf00-6e94-11eb-8638-d5ac25b67289.png)

For receiving files progress, I tried to implement it but I have some errors which I'm fixing now.

**Comment by moaz-mokhtar** [comment]
Thank Almighty Allah... I did it.

Receive print screen:
![image](https://user-images.githubusercontent.com/5870208/107893428-cab7f200-6f33-11eb-8084-7b69aee7d207.png)

Send print screen
![image](https://user-images.githubusercontent.com/5870208/107893418-c1c72080-6f33-11eb-8e48-49d2c88666b7.png)

 ====================== 
Notes:
1. I didn't commit or push yet, so seeking your guide.
2. After file sent and received, progress bar can be replaced with a message as below code.
```
pb.finish_print("Receive done");
```

> bp: is the PorgressBar struct.
> finish_print() a function to show a message under impl of ProgressBar.

**Comment by piegamesde** [comment]
Great, many thanks. You can simply put all of your changes in one commit and open a pull request so that we can all try it out and have a look at the code.

**Comment by piegamesde** [comment]
Implemented in #116.
